# Generated by Django 5.2 on 2025-04-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleepForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedtime', models.TimeField(verbose_name='Hora usual de deitar')),
                ('time_to_sleep', models.PositiveIntegerField(verbose_name='Minutos para dormir')),
                ('wakeup_time', models.TimeField(verbose_name='Hora usual de levantar')),
                ('sleep_hours', models.FloatField(verbose_name='Horas de sono por noite')),
                ('difficulty_falling_asleep', models.CharField(choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, verbose_name='Não conseguiu adormecer em até 30 minutos')),
                ('difficulty_staying_asleep', models.CharField(choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, verbose_name='Acordou no meio da noite ou de manhã cedo')),
                ('bathroom_visits', models.CharField(choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, verbose_name='Precisou levantar para ir ao banheiro')),
                ('breathing_difficulty', models.CharField(choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, verbose_name='Não conseguiu respirar confortavelmente')),
                ('coughing_snoring', models.CharField(choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, verbose_name='Tossiu ou roncou forte')),
                ('felt_cold', models.CharField(choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, verbose_name='Sentiu muito frio')),
                ('felt_hot', models.CharField(choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, verbose_name='Sentiu muito calor')),
                ('bad_dreams', models.CharField(choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, verbose_name='Teve sonhos ruins')),
                ('pain', models.CharField(choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, verbose_name='Teve dor')),
                ('other_reason', models.TextField(blank=True, null=True, verbose_name='Outra(s) razão(ões), por favor descreva')),
                ('other_reason_frequency', models.CharField(blank=True, choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, null=True, verbose_name='Frequência da outra razão')),
                ('sleep_quality', models.CharField(choices=[('4', 'Muito boa'), ('3', 'Boa'), ('2', 'Ruim'), ('1', 'Muito ruim')], max_length=1, verbose_name='Qualidade geral do sono')),
                ('medication_use', models.CharField(choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, verbose_name='Uso de medicamento para dormir')),
                ('daytime_sleepiness', models.CharField(choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, verbose_name='Dificuldade de ficar acordado durante atividades')),
                ('enthusiasm_difficulty', models.CharField(choices=[('0', 'Nenhuma dificuldade'), ('1', 'Um problema leve'), ('2', 'Um problema razoável'), ('3', 'Um grande problema')], max_length=1, verbose_name='Dificuldade em manter entusiasmo')),
                ('has_partner', models.CharField(choices=[('0', 'Não'), ('1', 'Parceiro ou colega, mas em outro quarto'), ('2', 'Parceiro no mesmo quarto, mas não na mesma cama'), ('3', 'Parceiro na mesma cama')], max_length=1, verbose_name='Tem parceiro/colega de quarto?')),
                ('partner_snoring', models.CharField(blank=True, choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, null=True, verbose_name='Ronco forte (observado por parceiro)')),
                ('partner_breathing_pauses', models.CharField(blank=True, choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, null=True, verbose_name='Longas paradas na respiração (observado por parceiro)')),
                ('partner_leg_movements', models.CharField(blank=True, choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, null=True, verbose_name='Contrações/puxões nas pernas (observado por parceiro)')),
                ('partner_confusion', models.CharField(blank=True, choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, null=True, verbose_name='Episódios de desorientação (observado por parceiro)')),
                ('partner_other_issues', models.TextField(blank=True, null=True, verbose_name='Outras alterações observadas (descreva)')),
                ('partner_other_frequency', models.CharField(blank=True, choices=[('0', 'Nenhuma no último mês'), ('1', 'Menos de 1 vez/semana'), ('2', '1 ou 2 vezes/semana'), ('3', '3 ou mais vezes/semana')], max_length=1, null=True, verbose_name='Frequência das outras alterações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
