# Generated by Django 5.2 on 2025-04-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleepForm', '0002_sleepquestionnaire_delete_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='bad_dreams',
            field=models.IntegerField(choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, verbose_name='Teve sonhos ruins'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='bathroom_visits',
            field=models.IntegerField(choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, verbose_name='Precisou levantar para ir ao banheiro'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='breathing_difficulty',
            field=models.IntegerField(choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, verbose_name='Não conseguiu respirar confortavelmente'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='coughing_snoring',
            field=models.IntegerField(choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, verbose_name='Tossiu ou roncou forte'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='daytime_sleepiness',
            field=models.IntegerField(choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, verbose_name='Dificuldade de ficar acordado durante atividades'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='difficulty_falling_asleep',
            field=models.IntegerField(choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, verbose_name='Não conseguiu adormecer em até 30 minutos'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='difficulty_staying_asleep',
            field=models.IntegerField(choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, verbose_name='Acordou no meio da noite ou de manhã cedo'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='enthusiasm_difficulty',
            field=models.IntegerField(choices=[(0, 'Nenhuma dificuldade'), (1, 'Um problema leve'), (2, 'Um problema razoável'), (3, 'Um grande problema')], max_length=1, verbose_name='Dificuldade em manter entusiasmo'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='felt_cold',
            field=models.IntegerField(choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, verbose_name='Sentiu muito frio'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='felt_hot',
            field=models.IntegerField(choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, verbose_name='Sentiu muito calor'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='has_partner',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Parceiro ou colega, mas em outro quarto'), (2, 'Parceiro no mesmo quarto, mas não na mesma cama'), (3, 'Parceiro na mesma cama')], max_length=1, verbose_name='Tem parceiro/colega de quarto?'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='medication_use',
            field=models.IntegerField(choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, verbose_name='Uso de medicamento para dormir'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='other_reason_frequency',
            field=models.IntegerField(blank=True, choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, null=True, verbose_name='Frequência da outra razão'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='pain',
            field=models.IntegerField(choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, verbose_name='Teve dor'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='partner_breathing_pauses',
            field=models.IntegerField(blank=True, choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, null=True, verbose_name='Longas paradas na respiração (observado por parceiro)'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='partner_confusion',
            field=models.IntegerField(blank=True, choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, null=True, verbose_name='Episódios de desorientação (observado por parceiro)'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='partner_leg_movements',
            field=models.IntegerField(blank=True, choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, null=True, verbose_name='Contrações/puxões nas pernas (observado por parceiro)'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='partner_other_frequency',
            field=models.IntegerField(blank=True, choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, null=True, verbose_name='Frequência das outras alterações'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='partner_snoring',
            field=models.IntegerField(blank=True, choices=[(0, 'Nenhuma no último mês'), (1, 'Menos de 1 vez/semana'), (2, '1 ou 2 vezes/semana'), (3, '3 ou mais vezes/semana')], max_length=1, null=True, verbose_name='Ronco forte (observado por parceiro)'),
        ),
        migrations.AlterField(
            model_name='sleepquestionnaire',
            name='sleep_quality',
            field=models.IntegerField(choices=[(4, 'Muito boa'), (3, 'Boa'), (2, 'Ruim'), (1, 'Muito ruim')], max_length=1, verbose_name='Qualidade geral do sono'),
        ),
    ]
