# .github/workflows/deploy.yml
name: Deploy Django app

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Django management commands
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          python manage.py collectstatic --noinput
          python manage.py migrate

      # Optionally: deploy step (push to hosting, e.g., Render/Fly.io/etc)
